### ISSUE TITLE
MainWP CSS affects WP core CSS

### ISSUE THREAD

**Issue by talss89** [mainwp/mainwp#4]
Not a big issue, but:

mainwp.css:151

``` css
#wpcontent, #footer {
margin-left: 165px;
}
```

This changes the horz position of the main content area in wp-admin. Not sure this is the right way to go, as it breaks full WP upgrade path support.

If I fork and submit a pull request, would you accept some CSS fix ups?
